### ISSUE TITLE
일기 쓰기 

### ISSUE THREAD

**Issue by lovysunny7** [shoesbox/shoesbox-fe#12]
- [x] 일기쓰기 뷰 #8 
- [x] 사진 미리보기 및 삭제 기능 #36 
- [x] 일기쓰기 데이터 바인딩 준비 (에디터X)- Jsondb #36 
- [x] 일기쓰기 데이터 바인딩 (에디터X) #56

**Comment by caffesale** [comment]
Branch [issue-12](https://github.com/shoesbox/shoesbox-fe/tree/issue-12) created!
