### ISSUE TITLE
상세 내용

### ISSUE THREAD

**Issue by lovysunny7** [shoesbox/shoesbox-fe#13]
- [x] 상세 보기 뷰 #1 
- [x] 상세, 댓글 보기 데이터 바인딩 - Jsondb #24 
- [x] 상세보기 데이터 바인딩 #24
- [x] 댓글 보기 데이터 바인딩 #36
- [x] 댓글 등록 데이터 바인딩 - Jsondb #30 
- [x] 댓글 등록 데이터 바인딩 #36
- [x] 댓글 수정 데이터 바인딩 - Jsondb #47
- [x] 댓글 수정 데이터 바인딩  #47
- [x] 댓글 삭제 데이터 바인딩 #36
- [x] 로그인 접근자에 따른 댓글 등록, 수정 보기 #56 
- [x] 로그인 접근자에 따른 수정하기, 삭제하가  #58
- [x] 상세 내용 수정하기 뷰 #67
- [x] 상세 내용 수정하기 데이터 바인딩 #67
- [x] 상세 내용 삭제하기 데이터 바인딩 #58
- [x] 상세보기 뷰_수정1 #16

**Comment by caffesale** [comment]
Branch [issue-13](https://github.com/shoesbox/shoesbox-fe/tree/issue-13) created!
