### ISSUE TITLE
친구 추가

### ISSUE THREAD

**Issue by lovysunny7** [shoesbox/shoesbox-fe#19]
- [x] 친구추가 뷰 #20 
- [x] 친구추가 요청 데이터 바인딩 #54 #56
- [x] 친구수락 데이터 바인딩 #54 #56
- [x] 친구거부 데이터 바인딩 #54 #56
- [x] 친구삭제 데이터 바인딩 #56
- [x] 내가 신청한 친구 목록 데이터 바인딩 #72 
- [x] 내가 신청한 친구 취소 데이터 바인딩 #72
- [ ] 추가적으로 구현한다면 소켓 같은 걸 이용하여 실시간 친구 요청 알림

**Comment by caffesale** [comment]
Branch [issue-19](https://github.com/shoesbox/shoesbox-fe/tree/issue-19) created!
